version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATA_PATH=./data
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge