[project]
name = "autogen_blog_project"
version = "0.1.0"
description = "Automated blog generation using AI agents."
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["autogen_blog"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
