name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          # Custom prompt for automatic implementation
          prompt: |
            You are working on implementing the tasks from the weekly-trend-worker specification.

            When tagged on an issue:
            1. Read the issue description and identify which tasks need to be implemented
            2. Create a new feature branch for the implementation
            3. Implement the requested tasks step by step according to the specifications in .kiro/specs/weekly-trend-worker/
            4. Create a pull request with a comprehensive description of what was implemented
            5. Update the issue with progress and link to the PR

            Focus on implementing one logical group of tasks per PR to make reviews manageable.

          # Enable Claude to create PRs and branches, commit code changes
          claude_args: '--allowed-tools Bash(gh pr:*) Bash(gh repo:*) Bash(git:*)'

